REVOKE ALL ON SCHEMA partman FROM partman_user;
REVOKE ALL ON ALL TABLES IN SCHEMA partman FROM partman_user;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA partman FROM partman_user;
REVOKE EXECUTE ON ALL PROCEDURES IN SCHEMA partman FROM partman_user;
REVOKE ALL ON SCHEMA public FROM partman_user;
DROP ROLE IF EXISTS partman_user;

DROP SCHEMA IF EXISTS partman CASCADE;
DROP EXTENSION IF EXISTS "pg_partman";
